SELECT * FROM customer_behavior.customer;
alter table customer_behavior.customer
rename column `Purchase Amount (USD)`TO Revenue;
# Question 1 What is the total revenue generated by male vs. female customers?
select `Gender` , sum(`Revenue`) as `total_revenue`
from `customer_behavior`.`customer`
group by `Gender`;

# Question 2 Which customers used a discount but still spent more than the average purchase amount?
select `Customer Id` ,`Revenue`
from `customer_behavior`.`customer`
where `Discount Applied`='Yes' and `Revenue`>= (select avg(`Revenue`)
from `customer_behavior`.`customer`);

# Question 3 Which are the top 5 products with the highest average review rating?
select `Item Purchased` ,round(avg(`Review Rating`) )as `avg_product_rating`
from `customer_behavior`.`customer`
group by `item Purchased`
order by `avg_product_rating` desc
limit 5;
#  Question 4 Compare the average purchase amount b/w Standard & Express Shipping
select `Shipping Type`, round(avg(`Revenue`),2)
from `customer_behavior`.`customer`
where `Shipping Type` in ('Standard','Express')
group by `Shipping Type`;
 
 # Question 5 Do subscibed Customers spent more ? Compare average Spend & Total revenue b/w subscribers & non - subscribers
select `Subscription Status`, count(`Customer ID`) as `total_customers`,
round(avg(`Revenue`),2) as `avg_revenue`,
round(sum(`Revenue`),2) as `total_revenue`
from `customer_behavior`.`customer`
group by `Subscription Status`
order by `avg_revenue`,`total_revenue` desc;

# Which 5 products have the highest percentage of purchases with discounts?
SELECT 
    `Item Purchased`,
    ROUND(SUM(CASE WHEN `Discount Applied` = 'Yes' THEN 1 ELSE 0 END) / COUNT(*) * 100, 2) AS `discount_rate`
FROM `customer_behavior`.`customer`
GROUP BY `Item Purchased`
order by `discount_rate` desc
limit 5;
# Question 7 Segment customers into new,returning & loyal based on their total number of previous purchases and show the count of each segment
WITH customer_type AS (
    SELECT 
        `Customer ID`, 
        `Previous Purchases`,
        CASE
            WHEN `Previous Purchases` = 1 THEN 'New'
            WHEN `Previous Purchases` BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS `Customer_Segment`
    FROM `customer_behavior`.`customer`
)
SELECT 
    `Customer_Segment`, 
    COUNT(*) AS `no_of_customers`
FROM customer_type
GROUP BY `Customer_Segment`;

# Question 9 What are the top 3 most Purchased products within each category?

WITH item_count AS (
    SELECT 
        `Category`,
        `Item Purchased`,
        COUNT(`Customer ID`) AS `total_orders`,
        ROW_NUMBER() OVER (PARTITION BY `Category` ORDER BY COUNT(`Customer ID`) DESC) AS `item_rank`
    FROM `customer_behavior`.`customer`
    GROUP BY `Category`, `Item Purchased`
)
SELECT  
    `item_rank`,
    `Category`,
    `Item Purchased`,
    `total_orders`
FROM item_count
WHERE `item_rank` <= 3;

# Question 10 Are customers who are repeat buyers(more than 5 purchases) also likely to subscribe?
select `Subscription Status`,
count(`Customer ID` ) as `repeat_buyers`
from `customer_behavior`.`customer`
where `Previous Purchases`>5
group by `Subscription Status`;

# Question 11 What is  revenue contibution of each age group?
select* from `customer_behavior`.`customer`;


